name: Databricks Migration Pipeline

on:
  push:
    branches:
      - dr-import
  workflow_dispatch:

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Databricks profiles
      run: |
        echo "[KELLANOVA_WORKSPACE_SOURCE_NEW]" >> ~/.databrickscfg
        echo "host = https://dbc-f074b72b-99f1.cloud.databricks.com" >> ~/.databrickscfg
        echo "token = ${{ secrets.DATABRICKS_TOKEN_SOURCE }}" >> ~/.databrickscfg
        echo "[KELLANOVA_WORKSPACE_DESTINATION_NEW]" >> ~/.databrickscfg
        echo "host = https://dbc-280cb907-6a02.cloud.databricks.com/" >> ~/.databrickscfg
        echo "token = ${{ secrets.DATABRICKS_TOKEN_DESTINATION }}" >> ~/.databrickscfg
        cat ~/.databrickscfg

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install setuptools deprecated
        python3 setup.py install

    - name: Download from S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        pip3 install boto3
        python3 -c "import os; import boto3; 
        os.environ['AWS_ACCESS_KEY_ID'] = '${{ secrets.AWS_ACCESS_KEY_ID }}'; 
        os.environ['AWS_SECRET_ACCESS_KEY'] = '${{ secrets.AWS_SECRET_ACCESS_KEY }}'; 
        os.environ['AWS_REGION'] = '${{ secrets.AWS_REGION }}'; 
        s3 = boto3.client('s3', region_name=os.environ['AWS_REGION']); 
        bucket_name = 'existing-source-bucket-1'; 
        s3_key = 'backups_123.zip';  
        s3.download_file(bucket_name, s3_key)"

    - name: Run Databricks Migration Pipeline
      run: |
        SRC_PROFILE=KELLANOVA_WORKSPACE_DESTINATION_NEW
        python3 migration_pipeline.py --profile $SRC_PROFILE --import-pipeline --use-checkpoint --session sample
